Cxl dvsec decoded
pciutils/pciutils pull request #120
Opened 2022-11-07 22:56 UTC by jphaws

This series decodes the remainder of the CXL capabilities that were left undecoded in #110. This includes:

- GPF DVSEC for CXL Devices (Section 8.1.7 of the CXL 3.0 spec)
- PCIe DVSEC for Flex Bus Port (Section 8.1.8 of the CXL 3.0 spec)
- GPF DVSEC for CXL Ports (Section 8.1.6 of the CXL 3.0 spec)
- MLD DVSEC (Section 8.1.10 of the CXL 3.0 spec)
- Non-CXL Function Map DVSEC (Section 8.1.4 of the CXL 3.0 spec)

Also includes a configuration space dump added to `tests/` of the CXL device I have access to.

2022-11-13 16:01 UTC, gollux requested changes
Generally, I like this, but I left a couple of nit-picking comments.

2022-11-17 16:13 UTC, jphaws commented on ls-ecaps.c
> +    printf("\t\tFBCap2:\t NOPHint%c\n", FLAG(l, PCI_CXL_FB_CTRL2_NOP_HINT));
No you are correct, that should have been `FBCtl2` and `FBSta2` below. Fixed that as well as space after `\t ` for each as well.

2022-11-17 16:20 UTC, jphaws commented on ls-ecaps.c
> +  if (rev < 1)
Added a warning: `Revision %d not supported`. Let me know if you'd like to see something else as the warning message or if that is acceptable.

2022-11-17 16:29 UTC, jphaws commented on ls-ecaps.c
> +  l = get_conf_word(d, where + PCI_CXL_FUN_MAP_REG_0);
Fixed

2022-11-18 08:26 UTC, merged

2022-11-18 08:26 UTC, gollux commented
Thanks, merged.